DROP DATABASE IF EXISTS roomstatedb;
CREATE DATABASE roomstatedb;
USE roomstatedb;

CREATE TABLE teacher(
id INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE room(
id INT NOT NULL AUTO_INCREMENT,
floor INT NOT NULL,
number VARCHAR(10),
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE lesson(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50),
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE room_lesson(
id INT NOT NULL AUTO_INCREMENT,
date_start DATE NOT NULL,
date_end DATE NOT NULL,
lesson_id INT NOT NULL,
room_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(lesson_id) REFERENCES lesson(id) ON DELETE CASCADE,
FOREIGN KEY(room_id) REFERENCES room(id) ON DELETE RESTRICT
)ENGINE=INNODB DEFAULT CHARSET=utf8;