DROP DATABASE IF EXISTS roomstatedb;
CREATE DATABASE roomstatedb;
USE roomstatedb;

CREATE TABLE teacher(
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE room(
id INT NOT NULL AUTO_INCREMENT,
number VARCHAR(10),
PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE lesson(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50),
date_start DATE NOT NULL,
date_end DATE NOT NULL,
room_id INT NOT NULL,
teacher_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(room_id) REFERENCES room(id) ON DELETE RESTRICT,
FOREIGN KEY(teacher_id) REFERENCES teacher(id) ON DELETE RESTRICT
)ENGINE=INNODB DEFAULT CHARSET=utf8;
